List<String> getLyrics() {
  return [
    'Ven, quiero un poco más',
    'salir de la realidad',
    'de ti me quiero embriagar.',
    'Ven, ven y calma esta ansiedad',
    'ilumina mi oscuridad',
    'y mis labios encontraras.',
    'Cada segundo te acercaras',
    'y nuestros cuerpos se fundirán',
    'y las palabras no bastarán',
    'para amarte y tomarte hoy.',
    'Hoy serás',
    'mi sueño eterno',
    'no quiero despertar',
    'te llevare',
    'donde nadie nos pueda encontrar',
    'donde nadie nos pueda...',
    '...',
    'Cada segundo te acercaras',
    'y nuestros cuerpos se fundirán',
    'y las palabras no bastarán',
    'para amarte y tomarte hoy.',
    'Hoy serás',
    'mi sueño eterno',
    'no quiero despertar',
    'te llevare',
    'donde nadie nos pueda encontrar',
    'donde nadie nos pueda…'
  ];
}
